# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(472, 291)
        SettingsDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(SettingsDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.browsingTab = QtWidgets.QWidget()
        self.browsingTab.setObjectName("browsingTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.browsingTab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkAdBlock = QtWidgets.QCheckBox(self.browsingTab)
        self.checkAdBlock.setObjectName("checkAdBlock")
        self.gridLayout_2.addWidget(self.checkAdBlock, 0, 0, 1, 2)
        self.checkFontLoad = QtWidgets.QCheckBox(self.browsingTab)
        self.checkFontLoad.setObjectName("checkFontLoad")
        self.gridLayout_2.addWidget(self.checkFontLoad, 2, 0, 1, 2)
        self.useragentEdit = QtWidgets.QLineEdit(self.browsingTab)
        self.useragentEdit.setObjectName("useragentEdit")
        self.gridLayout_2.addWidget(self.useragentEdit, 4, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 2)
        self.checkBlockPopups = QtWidgets.QCheckBox(self.browsingTab)
        self.checkBlockPopups.setObjectName("checkBlockPopups")
        self.gridLayout_2.addWidget(self.checkBlockPopups, 1, 0, 1, 1)
        self.label_UserAgent = QtWidgets.QLabel(self.browsingTab)
        self.label_UserAgent.setObjectName("label_UserAgent")
        self.gridLayout_2.addWidget(self.label_UserAgent, 3, 0, 1, 1)
        self.tabWidget.addTab(self.browsingTab, "")
        self.downloadTab = QtWidgets.QWidget()
        self.downloadTab.setObjectName("downloadTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.downloadTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkDownMan = QtWidgets.QCheckBox(self.downloadTab)
        self.checkDownMan.setObjectName("checkDownMan")
        self.verticalLayout_2.addWidget(self.checkDownMan)
        self.downManEdit = QtWidgets.QLineEdit(self.downloadTab)
        self.downManEdit.setObjectName("downManEdit")
        self.verticalLayout_2.addWidget(self.downManEdit)
        self.label_MediaPlayer = QtWidgets.QLabel(self.downloadTab)
        self.label_MediaPlayer.setObjectName("label_MediaPlayer")
        self.verticalLayout_2.addWidget(self.label_MediaPlayer)
        self.mediaPlayerEdit = QtWidgets.QLineEdit(self.downloadTab)
        self.mediaPlayerEdit.setObjectName("mediaPlayerEdit")
        self.verticalLayout_2.addWidget(self.mediaPlayerEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.downloadTab, "")
        self.appearanceTab = QtWidgets.QWidget()
        self.appearanceTab.setObjectName("appearanceTab")
        self.gridLayout = QtWidgets.QGridLayout(self.appearanceTab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_standard = QtWidgets.QLabel(self.appearanceTab)
        self.label_standard.setObjectName("label_standard")
        self.gridLayout.addWidget(self.label_standard, 1, 0, 1, 1)
        self.label_serif = QtWidgets.QLabel(self.appearanceTab)
        self.label_serif.setObjectName("label_serif")
        self.gridLayout.addWidget(self.label_serif, 3, 0, 1, 1)
        self.spinFontSize = QtWidgets.QSpinBox(self.appearanceTab)
        self.spinFontSize.setAlignment(QtCore.Qt.AlignCenter)
        self.spinFontSize.setMinimum(2)
        self.spinFontSize.setMaximum(24)
        self.spinFontSize.setObjectName("spinFontSize")
        self.gridLayout.addWidget(self.spinFontSize, 0, 1, 1, 1)
        self.fixedfontCombo = QtWidgets.QFontComboBox(self.appearanceTab)
        self.fixedfontCombo.setMaxVisibleItems(20)
        self.fixedfontCombo.setObjectName("fixedfontCombo")
        self.gridLayout.addWidget(self.fixedfontCombo, 4, 1, 1, 1)
        self.sansfontCombo = QtWidgets.QFontComboBox(self.appearanceTab)
        self.sansfontCombo.setMaxVisibleItems(20)
        self.sansfontCombo.setObjectName("sansfontCombo")
        self.gridLayout.addWidget(self.sansfontCombo, 2, 1, 1, 1)
        self.seriffontCombo = QtWidgets.QFontComboBox(self.appearanceTab)
        self.seriffontCombo.setMaxVisibleItems(20)
        self.seriffontCombo.setObjectName("seriffontCombo")
        self.gridLayout.addWidget(self.seriffontCombo, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.appearanceTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.standardfontCombo = QtWidgets.QFontComboBox(self.appearanceTab)
        self.standardfontCombo.setMaxVisibleItems(20)
        self.standardfontCombo.setObjectName("standardfontCombo")
        self.gridLayout.addWidget(self.standardfontCombo, 1, 1, 1, 1)
        self.label_fixed = QtWidgets.QLabel(self.appearanceTab)
        self.label_fixed.setObjectName("label_fixed")
        self.gridLayout.addWidget(self.label_fixed, 4, 0, 1, 1)
        self.label_sans = QtWidgets.QLabel(self.appearanceTab)
        self.label_sans.setObjectName("label_sans")
        self.gridLayout.addWidget(self.label_sans, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 2)
        self.tabWidget.addTab(self.appearanceTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_ClearCookies = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ClearCookies.sizePolicy().hasHeightForWidth())
        self.label_ClearCookies.setSizePolicy(sizePolicy)
        self.label_ClearCookies.setObjectName("label_ClearCookies")
        self.gridLayout_3.addWidget(self.label_ClearCookies, 1, 0, 1, 1)
        self.cookiesButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cookiesButton.sizePolicy().hasHeightForWidth())
        self.cookiesButton.setSizePolicy(sizePolicy)
        self.cookiesButton.setObjectName("cookiesButton")
        self.gridLayout_3.addWidget(self.cookiesButton, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 3, 0, 1, 2)
        self.label_IconDB = QtWidgets.QLabel(self.tab)
        self.label_IconDB.setObjectName("label_IconDB")
        self.gridLayout_3.addWidget(self.label_IconDB, 2, 0, 1, 1)
        self.iconDBButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconDBButton.sizePolicy().hasHeightForWidth())
        self.iconDBButton.setSizePolicy(sizePolicy)
        self.iconDBButton.setObjectName("iconDBButton")
        self.gridLayout_3.addWidget(self.iconDBButton, 2, 1, 1, 1)
        self.clearCacheButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearCacheButton.sizePolicy().hasHeightForWidth())
        self.clearCacheButton.setSizePolicy(sizePolicy)
        self.clearCacheButton.setObjectName("clearCacheButton")
        self.gridLayout_3.addWidget(self.clearCacheButton, 0, 1, 1, 1)
        self.label_ClearCache = QtWidgets.QLabel(self.tab)
        self.label_ClearCache.setObjectName("label_ClearCache")
        self.gridLayout_3.addWidget(self.label_ClearCache, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.checkAdBlock.setText(_translate("SettingsDialog", "Enable Adblock"))
        self.checkFontLoad.setText(_translate("SettingsDialog", "Block loading Fonts"))
        self.useragentEdit.setPlaceholderText(_translate("SettingsDialog", "Example: Firefox 40.0"))
        self.checkBlockPopups.setToolTip(_translate("SettingsDialog", "Do not allow webpages to open new tabs"))
        self.checkBlockPopups.setText(_translate("SettingsDialog", "Block Popup Tabs"))
        self.label_UserAgent.setText(_translate("SettingsDialog", "Custom UserAgent :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.browsingTab), _translate("SettingsDialog", "Browsing"))
        self.checkDownMan.setToolTip(_translate("SettingsDialog", "Start dwnload in external download manager"))
        self.checkDownMan.setText(_translate("SettingsDialog", "External Download Manager"))
        self.downManEdit.setToolTip(_translate("SettingsDialog", "This must contain %u in place of URL"))
        self.downManEdit.setPlaceholderText(_translate("SettingsDialog", "Example: wget -c %u"))
        self.label_MediaPlayer.setText(_translate("SettingsDialog", "Media player command :"))
        self.mediaPlayerEdit.setPlaceholderText(_translate("SettingsDialog", "Example: mplayer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.downloadTab), _translate("SettingsDialog", "Download && Media"))
        self.label_standard.setText(_translate("SettingsDialog", "Standard Font :"))
        self.label_serif.setText(_translate("SettingsDialog", "Serif Font :"))
        self.spinFontSize.setSuffix(_translate("SettingsDialog", " pt."))
        self.label.setText(_translate("SettingsDialog", "Min. Font Size :"))
        self.label_fixed.setText(_translate("SettingsDialog", "Fixed Font :"))
        self.label_sans.setText(_translate("SettingsDialog", "Sans Font :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appearanceTab), _translate("SettingsDialog", "Appearance"))
        self.label_ClearCookies.setText(_translate("SettingsDialog", "Cookies :"))
        self.cookiesButton.setText(_translate("SettingsDialog", "Clear Cookies"))
        self.label_IconDB.setText(_translate("SettingsDialog", "Icon DataBase :"))
        self.iconDBButton.setText(_translate("SettingsDialog", "Clear Icons"))
        self.clearCacheButton.setText(_translate("SettingsDialog", "Clear Cache"))
        self.label_ClearCache.setText(_translate("SettingsDialog", "Memory Cache :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingsDialog", "Data"))

